site_name: Tronic247 Material
site_url: https://material.tronic247.com
repo_url: https://github.com/Tronic247/material.tronic247.com
main_repo_url: https://github.com/Tronic247/material
edit_uri: edit/main/docs/
site_author: Posandu Mapa
copyright: Tronic247

theme:
    name: null
    custom_dir: 'theme'
    static_templates:
        - index.html
        - ads.txt
        - manifest.json
        - advertising.html